services:
  mongo:
    image: mongo
    container_name: appointments-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./api/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: appointments-api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: appointments-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - api

volumes:
  mongo_data:
